### ISSUE TITLE
Table resolution

### ISSUE THREAD

**Issue by zelenyhleb** [arsysop/loft-rgm#151]
Some tables cannot be resolved because of some powerful assumptions among algorithm implementation. Has to be investigated

**Comment by sovesti** [comment]
I looked through spec and found following few examples of tables that are different from others:

- [Table 73](https://timsong-cpp.github.io/cppwp/n4659/localization#tab:localization.integer.conversions.in) - here ```capsep``` doesn't separate title from table content, but breaks table content into two parts
- [Table 124](https://timsong-cpp.github.io/cppwp/n4659/fs.enum#tab:fs.enum.copy_options) - here four tables with own titles are stored in  one ```table``` element
- [Table 101](https://timsong-cpp.github.io/cppwp/n4659/numerics.general#tab:numerics.lib.summary) - here two columns have a common title
- [Table 23](https://timsong-cpp.github.io/cppwp/n4659/library#tab:moveconstructible) - I actually don't fully understand what did they mean by that, but it seems they took part that is same for each row in second column and put it into new row - with one column...
- [Table 13](https://timsong-cpp.github.io/cppwp/n4659/over#tab:over.conversions) - here few cells in one column are joined into one

All other tables probably can be resolved with current algorithm.
