### ISSUE TITLE
Split model into several parts

### ISSUE THREAD

**Issue by zelenyhleb** [arsysop/loft-rgm#19]
Now we have a mixed model with both _document_ and _language_ resources. It would be great to have these models separated.

**Comment by ruspl-afed** [comment]
Let's discuss it here, how about the following:

1) rgm.spec.ecore
   Document and its children

2) rgm.cpp.ecore
   Synopsis (Header) and its children

3) rgm.markup.ecore
  Markup and its children

**Comment by zelenyhleb** [comment]
>     3. rgm.markup.ecore
>        Markup and its children

Looks fine, but for me it's not clear enough, what is markup. Could you explain me, what do you mean, please?

**Comment by ruspl-afed** [comment]
Markup is a root element of "aggregating" model that holds a colection of "Interface Contracts" for particular class/function with all the references to spec, synopsis, requiremenst, whatever else.
"Interface Contract" should have enough details to create requirement-based tests for particular class/function.
